spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

app:
  cookie:
    refresh-token-name: refresh_token
    refresh-token-path: /api/v1/auth
    secure: true
    same-site: Lax

logging:
  level:
    root: INFO
    com.taskflow: INFO
