spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true

app:
  cookie:
    refresh-token-name: refresh_token
    refresh-token-path: /api/v1/auth
    secure: false
    same-site: Lax

logging:
  level:
    root: INFO
    com.taskflow: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
